# Lecture 3

In [1]:
%run set_env.py
%matplotlib inline

Check versions:
  numpy version     :'1.20.1'
  matplotlib version:'3.3.4'


## Indexing and Slicing

### 1D Array

Exactly as in regular python (<font color="green"><b>Nihil novi sub sole!</b></font>):
* Index: zero-based (like C)
* [start:end:step) i.e. half-open interval
   * start: (Default:0)
   * end: (Default: At the way to the end (inclusive))
   * step: (Default: +1)
* We can use negative indices:
   * -1: last el., etc.
* a[i]   : **indexing** vs. <br>
  a[j:m] : **slicing**

In [2]:
# 1D Example
a=np.arange(21)
print(f"a := np.arange(21) :\n  a         :  {a}")
print(f"  a[4]      :  {a[4]}")
print(f"  a[:]      :  {a[:]}")
print(f"  a[5:]     :  {a[5:]}")
print(f"  a[2:12:3] :  {a[2:12:3]}")
print(f"  a[2::5]   :  {a[2::5]}")
print(f"  a[-5:-1]  :  {a[-5:-1]}")
print(f"  a[-3:3:-1]:  {a[-3:3:-1]}")
print(f"  a[-7::2]  :  {a[-7::2]}")
print(f"  a[0]      :  {a[0]}")     # indexing -> EL.   => LOWER rank
print(f"  a[0:1]    :  {a[0:1]}")   # slicing  -> ARRAY => preserve rank

a := np.arange(21) :
  a         :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
  a[4]      :  4
  a[:]      :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
  a[5:]     :  [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
  a[2:12:3] :  [ 2  5  8 11]
  a[2::5]   :  [ 2  7 12 17]
  a[-5:-1]  :  [16 17 18 19]
  a[-3:3:-1]:  [18 17 16 15 14 13 12 11 10  9  8  7  6  5  4]
  a[-7::2]  :  [14 16 18 20]
  a[0]      :  0
  a[0:1]    :  [0]


### N-Dimensional Array

* Indexing & slicing are quite similar as for regular Python
* <font color="red"><b>MAIN DIFFERENCE</b></font>: 
  * [i][j] (Python) 
  * becomes [i,j] (NumPy)
 

In [3]:
# Example
print("  NUMPY::")
x = np.array([3**i for i in range(8)]).reshape(2,4)
print(f"  x:\n{x}\n")
print(f"  x[0,0] :{x[0,0]}")
print(f"  x[1,2] :{x[1,2]}")
print(f"  x[1,:] :{x[1,:]}")
print(f"  x[1]   :{x[1]}")
print(f"  x[:,-1]:{x[:,-1]}\n")

print("  REGULAR PYTHON::")
x = x.tolist()
print(f"  x:\n{x}\n")
print(f"  x[0][0] :{x[0][0]}")
print(f"  x[1][2] :{x[1][2]}")
print(f"  x[1][:] :{x[1][:]}") 
print(f"  x[1]    :{x[1]}")
print(f"  x[:][-1]:{x[:][-1]}")       # SEEMINGLY WRONG RESULT!!!! What's going on?

  NUMPY::
  x:
[[   1    3    9   27]
 [  81  243  729 2187]]

  x[0,0] :1
  x[1,2] :729
  x[1,:] :[  81  243  729 2187]
  x[1]   :[  81  243  729 2187]
  x[:,-1]:[  27 2187]

  REGULAR PYTHON::
  x:
[[1, 3, 9, 27], [81, 243, 729, 2187]]

  x[0][0] :1
  x[1][2] :729
  x[1][:] :[81, 243, 729, 2187]
  x[1]    :[81, 243, 729, 2187]
  x[:][-1]:[81, 243, 729, 2187]


In [4]:
# Explanation (i.e. Under the Hood)
print(f"  x[:]   : {x[:]}")
print(f"  len(x) : {len(x)}")
y = x[:]
print(f"  y[-1]  : {y[-1]}")

# THEREFORE:
res =[ item[-1] for item in y]
print(f"  res    : {res}")

  x[:]   : [[1, 3, 9, 27], [81, 243, 729, 2187]]
  len(x) : 2
  y[-1]  : [81, 243, 729, 2187]
  res    : [27, 2187]


<font color="green"><b>NOTE: Numpy slicing has some additional features:</b></font><br>
 * if #indices < #dim: Assumes ALL of the remaining dimensions
 * ellipsis: ... : Consider complete dimensions up to the index
 * axis          : Synonymous for dimension (C style)
 * index  : lowering of dimensionality -> <b>always COPY</b>
 * slicing: preserves dimensionality   -> <b>always VIEW</b>

In [5]:
a = rnd.random((3,4,5,6,7,6))
print(f"  a.shape:{a.shape}")
b = a[0:2,0:1]  # Slice in 2nd dim. ->  preserve dimensionality
print(f"  b.shape:{b.shape}") 
c = a[0:2,0]    # Index for 2nd dim. -> lowering dimensionality
print(f"  c.shape:{c.shape}")

  a.shape:(3, 4, 5, 6, 7, 6)
  b.shape:(2, 1, 5, 6, 7, 6)
  c.shape:(2, 5, 6, 7, 6)


### Slicing, indexing: View vs. Copy

#### Slicing:

In [26]:
a = np.random.random((5,5))
print(f" a:\n{a}\n")

# B is a slice of A => VIEW
b = a[3:4,3:4]
print(f" b:\n{b}\n")
print(f" b.flags:\n{b.flags}\n")

#Modifying B:
b[:,:]=0.0
print(f" b:\n{b}\n")
print(f" a:\n{a}\n")

 a:
[[0.6005 0.5366 0.3474 0.2921 0.1375]
 [0.3538 0.5446 0.8767 0.1993 0.0615]
 [0.3074 0.3863 0.1956 0.4775 0.7104]
 [0.0827 0.7281 0.9987 0.7443 0.9145]
 [0.3228 0.0833 0.5194 0.8159 0.0134]]

 b:
[[0.7443]]

 b.flags:
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


 b:
[[0.]]

 a:
[[0.6005 0.5366 0.3474 0.2921 0.1375]
 [0.3538 0.5446 0.8767 0.1993 0.0615]
 [0.3074 0.3863 0.1956 0.4775 0.7104]
 [0.0827 0.7281 0.9987 0.     0.9145]
 [0.3228 0.0833 0.5194 0.8159 0.0134]]



#### Working on copy of a slice:

In [7]:
a = np.random.random((5,5))
print(f" a:\n{a}\n")

# C is NOT a view BUT a copy
c = a[3:5,3:5].copy()
print(f" c:\n{c}\n")
print(f" c.flags:\n{c.flags}\n")

# Modifying C:
c[:,:] = -1.0
print(f" c:\n{c}\n")
print(f" a:\n{a}\n")

 a:
[[0.61742833 0.28193953 0.52047071 0.61866622 0.07796352]
 [0.6606416  0.99755799 0.33075169 0.42831698 0.26439284]
 [0.19575688 0.13660916 0.14983247 0.10108075 0.03133373]
 [0.15958754 0.78919555 0.43324334 0.16774277 0.78575313]
 [0.05879238 0.92142664 0.26602486 0.90785145 0.34120057]]

 c:
[[0.16774277 0.78575313]
 [0.90785145 0.34120057]]

 c.flags:
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


 c:
[[-1. -1.]
 [-1. -1.]]

 a:
[[0.61742833 0.28193953 0.52047071 0.61866622 0.07796352]
 [0.6606416  0.99755799 0.33075169 0.42831698 0.26439284]
 [0.19575688 0.13660916 0.14983247 0.10108075 0.03133373]
 [0.15958754 0.78919555 0.43324334 0.16774277 0.78575313]
 [0.05879238 0.92142664 0.26602486 0.90785145 0.34120057]]



#### Example of indexing:

In [ ]:
# D is obtained by pure indexing
a = np.random.random((5,5))
print(f" a:\n{a}\n")

d = a[1,2]
print(f" d:\n{d}\n")
print(f" d.flags:\n{d.flags}\n")

### What about reshaping?

<i>From the Numpy manual</i>:<br>
It is <b>not always</b> possible to change the shape of an array without copying the data.


#### a. Example of reshaping without copying

In [ ]:
# Default Memory layout is C
x = np.random.random((4,6))
print(f" x (Orig.):\n{x}\n")
print(f" x.flags:\n{x.flags}\n")
y=x.reshape((6,4))
print(f" x (After Reshaping):\n{y}\n")
print(f" x.flags:\n{y.flags}")

#### b.More problematic case:

Note:<br>
We can create a view on an ndarray using the view method (vide infra)

In [ ]:
# Create a rdn matrix A
a = np.random.random((4,6))
print(f" a:\n{a}\n")
print(f" a.flags:\n{a.flags}")

In [ ]:
b = a.T
print(f" b:\n{b}\n")
print(f" b.flags:\n{b.flags}")

In [ ]:
# We FORCE to be a view on b
c = b.view()
print(f" c:\n{c}\n")
print(f" c.flags:\n{c.flags}")

In [ ]:
# Force c to reshape to a. 
# This requires a copy (can't because it is a VIEW) => Error
c.shape=(4,6)

### Exercises:

* <b>Exercise 3.1</b>: 
  * Generate the following $2D$ matrix A:<br>
    $$\begin{bmatrix}
      1 & 2 & 3 & 4 & 5  & 6\\
      7 & 8 & 9 & 10 & 11 & 12\\ 
      13 & 14 & 15 & 16 & 17 & 18 \\
      19 & 20 & 21 & 22 & 23 & 24\\
      25 & 26 & 27 & 28 & 29 & 30
      \end{bmatrix}$$
  * Extract the following $2D$ matrix B from A:<br>
    $$\begin{bmatrix}
       1 & 3 \\
       7 & 9 \\
      13 & 15 \\
      19 & 21 \\
      25 & 27
      \end{bmatrix}$$
  * Extract the following $1D$ vector C from A:<br>
    $$\begin{bmatrix}
      8 & 10 & 12
      \end{bmatrix}$$ 
  * Could you extract the same object as a $2D$ matrix?  
  * Extract the following $2D$ matrix E from A:<br>
    $$\begin{bmatrix}
      2 & 5 \\
      20 & 23
      \end{bmatrix}$$
* <b>Exercise 3.2</b>:
  * Create a random matrix (7x7) with values $[0.0,1.0)$:<br>
    Replace the core 3x3 matrix of the above matrix with ones.<br>
    (Hint: use the np.random.random function to create the matrix)
* <b>Exercise 3.3</b>:
  * Create the following (8x8) checkerboard containing 0 and 1's (type integer) in 2 different ways:
    $$\begin{bmatrix}
      0 & 1 & 0 & 1 &  0 & 1 & 0 & 1\\
      1 & 0 & 1 &  0 & 1 & 0 & 1 & 0\\
      0 & 1 & 0 & 1 &  0 & 1 & 0 & 1\\
      1 & 0 & 1 &  0 & 1 & 0 & 1 & 0\\
      0 & 1 & 0 & 1 &  0 & 1 & 0 & 1\\
      1 & 0 & 1 &  0 & 1 & 0 & 1 & 0\\
      0 & 1 & 0 & 1 &  0 & 1 & 0 & 1 \\
      1 & 0 & 1 &  0 & 1 & 0 & 1 & 0
      \end{bmatrix}$$
    * ONLY using slicing
    * using the numpy np.tile function (use help to find the syntax)

### Solution:

In [ ]:
# %load ../solutions/ex3.py

In [35]:
A = np.arange(1,31).reshape((5,6))
A
A1=A[:,0:3:2]
print(A1)
A2=A[1,1::2]
print(A2)
A3=A[1:2,1::2]
print(A3)
A4 =A[0::3, 1::3]
print(A4)

[[ 1  3]
 [ 7  9]
 [13 15]
 [19 21]
 [25 27]]
[ 8 10 12]
[[ 8 10 12]]
[[ 2  5]
 [20 23]]


In [18]:
# 3.2
np.set_printoptions(precision=4)
B = rnd.random((7,7))
B[2:5,2:5]=0.0
B

array([[0.9614, 0.7606, 0.2724, 0.5104, 0.9874, 0.0526, 0.0868],
       [0.3374, 0.8037, 0.7284, 0.3894, 0.4551, 0.8864, 0.0145],
       [0.993 , 0.106 , 0.    , 0.    , 0.    , 0.5284, 0.0682],
       [0.961 , 0.9055, 0.    , 0.    , 0.    , 0.1991, 0.5308],
       [0.2997, 0.3603, 0.    , 0.    , 0.    , 0.5914, 0.0217],
       [0.2895, 0.4488, 0.8675, 0.0081, 0.5394, 0.7965, 0.2505],
       [0.5   , 0.7562, 0.2532, 0.2258, 0.5305, 0.5604, 0.6871]])

In [39]:
# Checkerboard
A = np.ones((8,8),dtype='int64')
print(A)
A[0::2,0::2]=0
print(A)
A[1::2,1::2]=0
print(A)


[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]
[[0 1 0 1 0 1 0 1]
 [1 1 1 1 1 1 1 1]
 [0 1 0 1 0 1 0 1]
 [1 1 1 1 1 1 1 1]
 [0 1 0 1 0 1 0 1]
 [1 1 1 1 1 1 1 1]
 [0 1 0 1 0 1 0 1]
 [1 1 1 1 1 1 1 1]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [40]:
np.tile?

In [41]:
np.tile([[0,1],[1,0]],(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])