# Lecture 4

In [1]:
%run set_env.py
%matplotlib inline

Check versions:
  numpy version     :'1.20.1'
  matplotlib version:'3.3.4'


### Vector Operations & Broadcasting

* NumPy operations are done on an <b><font color="green">element-by-element</font></b> basis

In [ ]:
# Regular Python: '+'/'*' 
N = 5
x = [i for i in range(N)]
y = N*[1]
print(f"  x  :{x}")
print(f"  y  :{y}")
print(f"  x+y:{x+y}")  # extend method for lists

In [ ]:
# Numpy's addition
x = np.array(x)
y = np.array(y)
print(f"  x  :\n{x}")
print(f"  y  :\n{y}")
print(f"  x+y:\n{x+y}")

<b>Note</b>:<br>
The '*' operator is overriden in NumPy as well.<br>
What is the diffference?

#### Examples:

In [ ]:
# Numpy's Multiplication
x = rnd.randint(3,10,(4,4))
y = rnd.randint(1,5,(4,4))
print(f"  x:\n{x}\n")
print(f"  y:\n{y}\n")
print(f"  x*y:\n{x*y}\n")

In [ ]:
# b. Boolean operators working on NumPy arrays
x = rnd.randint(4,10,(12))
y = rnd.randint(4,10,(12))
print(f"  x={x}")
print(f"  y={y}\n")
print(f"  ==      : {x==y}")
print(f"  !=      : {x!=y}")
print(f"  not(!=) : {~(x!=y)}")
print(f"  >=      : {x>=y}")
print(f"  x>7     : {x>7}")

# There are also bit operators
# To combine logical operations: &, |, ^, ~

## Matrices
# also --> el. by. el.
# How to do matrix multiplicationn??
# There is a native 2D matrix type -> do not use!

#### Combining boolean operators for ndarray objects


<font color="green"><b>Regular python</b></font> : 
* and  
* or  (inclusive or)
* not (negation operator)
* !=  (exclusive or)
 

In [ ]:
# Combining boolean operators as in REGULAR'Python' way -> ERROR
# x < 5 or y>7
# (Due to DIFFERENT syntax!)

<font color="green"><b>Numpy</b></font>:
* & : and operator
* | : inclusive or operator
* ~ : negation operator
* ^ : exclusive or (xor)

In [ ]:
# Combining boolean operators in NumPy
print(f"  x                 : {x}")
print(f"  y                 : {y}\n")
v1 = (x<8) & (x>4)
print(f"  (x<8) & (x>4)     : {v1}")
v2 = (x<6) | (x>7)
print(f"  (x<6) | (x>7)     : {v2}")
v3 = ~(x==6)
print(f"  ~(x==6)           : {v3}")
v4 = (x<6) ^ (x<7)   
print(f"  (x<6) ^ (x<7)     : {v4}")

### How to perform matrix multiplications in Numpy?

* Numpy operators work in an el. by el. fashion
* To perform matrix multiplications in numpy -> <font color="green"><b>np.dot</b></font> function

#### Examples:

In [ ]:
# np.dot (1D case)
a = rnd.randint(4,10,(10))
b = rnd.randint(1,5,(10))

print(f"  a                 : {a}")
print(f"  b                 : {b}")
print(f"  a.b (dot-product) : {np.dot(a,b)}")
print(f"  a.b (dot.product) : {np.sum(a*b)}")

In [ ]:
# np.dot (2D case) -> Matrix Multiplication
c = rnd.randint(4,10,(2,4))
d = rnd.randint(1,5,(4,3))

print(f"  c:\n {c}\n")
print(f"  d:\n {d}\n")
print(f"  c.d (Matrix Multiplication):\n {np.dot(c,d)}")

## Broadcasting

Let's start with a few simple examples/tests ...

#### Example 1:

In [ ]:
x = np.arange(1,5)
y = np.arange(10,50,10)
print(f"  x      : {x}")
print(f"  x.shape: {x.shape}\n")
print(f"  y      : {y}")
print(f"  y.shape: {y.shape}\n")
print(f"  x+y        : {x+y}")
print(f"  (x+y).shape: {(x+y).shape}")

#### Example 2:

In [ ]:
x = np.arange(1,5)
y = np.arange(1,4)
print(f"  x      : {x}")
print(f"  x.shape: {x.shape}\n")
print(f"  y  : {y}".format(y))
print(f"  y.shape: {y.shape}\n")
print(f"  x+y: {x+y}")

#### Example 3:

In [ ]:
# Example 3:
x = np.arange(1,5)
y = np.random.randint(0,11,(3,4))
print(f"  x  : \n{x}")
print(f"  x.shape: {x.shape}\n")
print(f"  y  : \n{y}")
print(f"  y.shape: {y.shape}\n")
print(f"  x+y: \n{x+y}")

### The rules of the (broadcasting) game

* Definition :: required to operate on (some) arrays with <b>(seemingly) mismatched</b> shapes
* Start with the trailing dimensions (i.e. from right to left)
* Two dimensions of the array are <b>compatible</b> iff
  * they both have the <b>same</b> dimension
  * <b>one</b> of the dimension is 1

Note:<br>
<font color="green"><b>Both arrays can have a different #axes</b></font>

#### Examples:

In [ ]:
# Example 1
# Res: x: 4 x 1
#      y:     5
# -------------
#    x+y: 4 x 5
#---------------
x = rnd.random(4).reshape(4,1)
y = np.arange(5)
print(f"  x  : \n{x}")
print(f"  y  : \n{y}")
print(f"  x+y: \n{x+y}")

In [ ]:
# Example 2
# Res: x: 13 x 1 x 7 x 1
#      y:      8 x 7 x 5
# -------------
#    res: 13 x 8 x 7 x 5
#---------------
x=np.arange(91).reshape((13,1,7,1))
y=np.arange(8*7*5).reshape((8,7,5))
z=x+y
print(f"  x.shape:{x.shape}")
print(f"  y.shape:{y.shape}")
print(f"  z.shape:{z.shape}")

In [ ]:
# Example 3:
# Res: x: 3 x 8 x 3
#      y:     3 x 1
# -------------
#    res:     Error !! (8 & 3)
#---------------
x=np.arange(72).reshape((3,8,3))
y=np.arange(9).reshape((3,3))
z=x+y
print(f"  x.shape:{x.shape}")
print(f"  y.shape:{y.shape}")
print(f"  z.shape:{z.shape}")

### Adding & Removing Singleton Dimensions

Axes of dim 1 (singleton dimensions) are a central tool for broadcasting.<br>
There are situations in which, one wants to:
* <b>remove</b> singleton dimensions:
  * use <b><font color="green">numpy.squeeze(a,axis=None)</font></b>
    * a: input data
    * axis : integer/tuple
    * default: all singleton dimensions
  
* <b>add</b> singleton dimensions:
  * use <b><font color="green">numpy.newaxis</font></b>
    * expand the dimension by 1 unit
    * to be added where you want to add the dimension

#### Examples:

In [ ]:
# np.squeeze() function i.e. Removing Singleton axes
a=np.arange(120).reshape((2,1,3,5,1,4))
print(f"  a.shape: {a.shape}")
b=np.squeeze(a,axis=1)
print(f"  b.shape: {b.shape}")
c=np.squeeze(a,axis=4)
print(f"  c.shape: {c.shape}")
d=np.squeeze(a)
print(f"  d.shape: {d.shape}")

In [ ]:
# Adding Singleton Axes
a = np.arange(24).reshape((2,3,4))
print(f"  a.shape: {a.shape}")
b = a[np.newaxis,:,:,:]
print(f"  b.shape: {b.shape}")
c = a[np.newaxis,...]
print(f"  c.shape: {c.shape}")
d=a[:,np.newaxis,:,:,np.newaxis]
print(f"  d.shape: {d.shape}")

### Exercises:

* Create the following 6x6 matrix $A$ (containing only <font color="green"><b>int32</b></font> elements)):<br>
    $\begin{equation*}A = \begin{pmatrix}
       1 & 1 &  1 &   1 &   1 &   1 \\
       1 & 8 &  1 &   1 &   1 &   1 \\ 
       1 & 1 &  27 &   1 &   1 &   1 \\
       1 & 1 &  1 &   64 &   1 &   1 \\
       1 & 1 &  1 &   1 &  125 &   1 \\
       1 & 1 &  1 &   1 &   1 &   216 
      \end{pmatrix}\end{equation*}$
* Create a new matrix $B$ ($MxN$) where:
  * $\begin{equation*}B_{ij} =  \frac{1}{X_i - Y_j} \end{equation*}$
  * $X_i$ $\in$ $X$  ($i=0,\ldots,M-1$)<br>
    is a random vector of length $M=9$ 
  * $Y_j$ $\in$ $Y$  ($j=0,\ldots,N-1$)<br>
    is a random vector of length $N=6$ 
    
  Matrices of the type $B$ are known as <font color="blue"><b>Cauchy</b></font> matrices 
  

### Solutions:

In [ ]:
# %load ../solutions/ex4.py

In [2]:
import numpy as np
A = np.ones((6,6)) + np.diag([i**3 -1 for i in range(1,7)])
print(A.astype('int32'))

[[  1   1   1   1   1   1]
 [  1   8   1   1   1   1]
 [  1   1  27   1   1   1]
 [  1   1   1  64   1   1]
 [  1   1   1   1 125   1]
 [  1   1   1   1   1 216]]


In [6]:
import numpy.random as rnd
np.set_printoptions(precision=4)
X = rnd.random((9))
Y = rnd.random((6))
print(X)
print(Y)
B= 1./(X[:,np.newaxis] -Y)
print(B)

[0.9544 0.345  0.5951 0.6981 0.411  0.7395 0.727  0.0245 0.1893]
[0.5058 0.5981 0.2168 0.04   0.2013 0.497 ]
[[   2.2288    2.8068    1.3556    1.0936    1.3278    2.1862]
 [  -6.222    -3.9509    7.7954    3.2781    6.957    -6.5798]
 [  11.1881 -332.5895    2.6428    1.8013    2.5391   10.1916]
 [   5.198    10.0007    2.0774    1.5194    2.0127    4.9721]
 [ -10.5547   -5.3438    5.1478    2.6952    4.7684  -11.6272]
 [   4.2782    7.0744    1.913     1.4296    1.858     4.124 ]
 [   4.52      7.7609    1.9599    1.4556    1.9022    4.3482]
 [  -2.0781   -1.7434   -5.2024  -64.7572   -5.6575   -2.1165]
 [  -3.1602   -2.446   -36.4478    6.6962  -83.4917   -3.2499]]
