# Lecture 7

In [1]:
%run set_env.py
%matplotlib inline

Check versions:
  numpy version     :'1.24.3'
  matplotlib version:'3.8.2'


## Assembling & splitting up ndarrays

### a.Stacking ndarrays

* vstack, hstack each concatenate <font color="green"><b>along an axis</b></font>.
* All functions <font color="green"><b>REQUIRE a tuple</b></font> as input.

In [2]:
# VSTACK & CONCATENATE:
# --------------------
a = np.arange(1,10).reshape(3,3)
b = np.arange(10,100,10).reshape((3,3))

print(f"  a:\n{a}")
print(f"  b:\n{b}")
print(f"  Vertical Stacking w. 'np.vstack':\n{np.vstack((a,b))}\n")
print(f"  Vertical Stacking w. 'np.concatenate' along rows (axis=0):\n{np.concatenate((a,b),axis=0)}\n")

  a:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
  b:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
  Vertical Stacking w. 'np.vstack':
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]
 [40 50 60]
 [70 80 90]]

  Vertical Stacking w. 'np.concatenate' along rows (axis=0):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]
 [40 50 60]
 [70 80 90]]



In [3]:
# HSTACK & CONCATENATE:
# --------------------
a = np.arange(1,10).reshape(3,3)
c = np.arange(18,36).reshape(3,6)
print(f"  a:\n{a}\n")
print(f"  c:\n{c}\n")
res1_ac = np.hstack((a,c))
print(f"  Horizontal Stacking w. 'np.hstack':\n{res1_ac}\n")
res1_ca = np.hstack((c,a))
print(f"  Horizontal Stacking w. 'np.hstack':\n{res1_ca}\n")
res2_ac = np.concatenate((a,c),axis=1)
print(f"  Horizontal Stacking w. 'np.concatenate' along rows (axis=1):\n{res2_ac}\n")

  a:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

  c:
[[18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

  Horizontal Stacking w. 'np.hstack':
[[ 1  2  3 18 19 20 21 22 23]
 [ 4  5  6 24 25 26 27 28 29]
 [ 7  8  9 30 31 32 33 34 35]]

  Horizontal Stacking w. 'np.hstack':
[[18 19 20 21 22 23  1  2  3]
 [24 25 26 27 28 29  4  5  6]
 [30 31 32 33 34 35  7  8  9]]

  Horizontal Stacking w. 'np.concatenate' along rows (axis=1):
[[ 1  2  3 18 19 20 21 22 23]
 [ 4  5  6 24 25 26 27 28 29]
 [ 7  8  9 30 31 32 33 34 35]]



### b.Splitting ndarrays

* np.split(arr,indices/sections, axis=0): split along an <b>axis</b> into multiple sub-arrays as views.
  * if indices (n): split arr into n <b>equal</b> parts along axis.
  * sections e.g [2,4]: create subarrays: arr[:2], arr[2:4], arr[4:]
* np.vsplit(arr, [indices/sections]): np.split along <b>axis=0</b> (rows).
* np.hsplit(arr, [indices/sections]): np.split along <b>axis=1</b> (columns)

In [4]:
# Vertical split
A = np.arange(48).reshape((6,8))
print(f"  A:\n{A}\n")
print(f"  Vertical split in 3 EQUAL parts:\n")
A_1, A_2, A_3 = np.vsplit(A,3)
print(f"    A_1:\n{A_1}\n")
print(f"    A_2:\n{A_2}\n")
print(f"    A_3:\n{A_3}\n")

  A:
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]]

  Vertical split in 3 EQUAL parts:

    A_1:
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]

    A_2:
[[16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]

    A_3:
[[32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]]



In [5]:
print(f"  A:\n{A}\n")
print(f"  Vertical split into SECTIONS:\n")
A_1, A_2, A_3 = np.vsplit(A,[1,4])
print(f"    A_1  A[ :1]:\n{A_1}\n")
print(f"    A_2  A[1:4]:\n{A_2}\n")
print(f"    A_3  A[4: ]:\n{A_3}\n")
# The same can be done using np.split but requires an
# ADDITIONAL argument, i.e. axis=0

  A:
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]]

  Vertical split into SECTIONS:

    A_1  A[ :1]:
[[0 1 2 3 4 5 6 7]]

    A_2  A[1:4]:
[[ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]

    A_3  A[4: ]:
[[32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]]



In [6]:
# Horizontal split (Part 1)
B = np.arange(32).reshape((4,8))
print(f"  B:\n{B}\n")
print(f"  Horizontal split in 2 EQUAL parts::\n")
B_1, B_2 = np.hsplit(B,2)
print(f"    B_1:\n{B_1}\n")
print(f"    B_2:\n{B_2}\n")

  B:
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]

  Horizontal split in 2 EQUAL parts::

    B_1:
[[ 0  1  2  3]
 [ 8  9 10 11]
 [16 17 18 19]
 [24 25 26 27]]

    B_2:
[[ 4  5  6  7]
 [12 13 14 15]
 [20 21 22 23]
 [28 29 30 31]]



In [7]:
# Horizontal split (Part 2)
print(f"  B:\n{B}\n")
print(f"  Horizontal split INTO sections::\n")
B_1, B_2, B_3, B_4 = np.hsplit(B,[1,3,5])
print(f"    B_1 [ :1]:\n{B_1}\n")
print(f"    B_2 [1:3]:\n{B_2}\n")
print(f"    B_3 [3:5]:\n{B_3}\n")
print(f"    B_4 [5: ]:\n{B_4}\n")
# The same can be done using np.split but requires an
# ADDITIONAL argument, i.e. axis=1

  B:
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]

  Horizontal split INTO sections::

    B_1 [ :1]:
[[ 0]
 [ 8]
 [16]
 [24]]

    B_2 [1:3]:
[[ 1  2]
 [ 9 10]
 [17 18]
 [25 26]]

    B_3 [3:5]:
[[ 3  4]
 [11 12]
 [19 20]
 [27 28]]

    B_4 [5: ]:
[[ 5  6  7]
 [13 14 15]
 [21 22 23]
 [29 30 31]]



### c.Blocks

* np.block: assemble an ndarray from nested lists of blocks.

In [8]:
A = np.ones((2,3))
B = np.full((2,5), np.e)
C = np.full((3,4), np.pi)
D = np.ones((3,4))
np.set_printoptions(precision=3)
print(f"    Blocks:\n")
print(f"      A = np.ones((2,3)) ::\n{A}\n")
print(f"      B = np.full((2,5), np.e) ::\n{B}\n")
print(f"      C = np.full((3,4), np.pi) ::\n{C}\n")
print(f"      D = np.ones((3,4)) ::\n{D}\n")
E = np.block([[A,B],[C,D]])
print(f"      E = np.block([[A,B],[C,D]] ::\n{E}\n")

    Blocks:

      A = np.ones((2,3)) ::
[[1. 1. 1.]
 [1. 1. 1.]]

      B = np.full((2,5), np.e) ::
[[2.718 2.718 2.718 2.718 2.718]
 [2.718 2.718 2.718 2.718 2.718]]

      C = np.full((3,4), np.pi) ::
[[3.142 3.142 3.142 3.142]
 [3.142 3.142 3.142 3.142]
 [3.142 3.142 3.142 3.142]]

      D = np.ones((3,4)) ::
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

      E = np.block([[A,B],[C,D]] ::
[[1.    1.    1.    2.718 2.718 2.718 2.718 2.718]
 [1.    1.    1.    2.718 2.718 2.718 2.718 2.718]
 [3.142 3.142 3.142 3.142 1.    1.    1.    1.   ]
 [3.142 3.142 3.142 3.142 1.    1.    1.    1.   ]
 [3.142 3.142 3.142 3.142 1.    1.    1.    1.   ]]



## B. Info on regular Numpy types:

In [9]:
print(np.finfo(np.float64))
print(np.finfo(np.complex128))
print(np.iinfo(np.int8))

Machine parameters for float64
---------------------------------------------------------------
precision =  15   resolution = 1.0000000000000001e-15
machep =    -52   eps =        2.2204460492503131e-16
negep =     -53   epsneg =     1.1102230246251565e-16
minexp =  -1022   tiny =       2.2250738585072014e-308
maxexp =   1024   max =        1.7976931348623157e+308
nexp =       11   min =        -max
smallest_normal = 2.2250738585072014e-308   smallest_subnormal = 4.9406564584124654e-324
---------------------------------------------------------------

Machine parameters for float64
---------------------------------------------------------------
precision =  15   resolution = 1.0000000000000001e-15
machep =    -52   eps =        2.2204460492503131e-16
negep =     -53   epsneg =     1.1102230246251565e-16
minexp =  -1022   tiny =       2.2250738585072014e-308
maxexp =   1024   max =        1.7976931348623157e+308
nexp =       11   min =        -max
smallest_normal = 2.2250738585072014e-30

## C. Special types in Numpy

* Regular Python throws a <font color="red"><b>ZeroDivisonError</b></font> when trying 
to divide a number by <font color="red"><b>0</b></font>.
* You can always <font color="green"><b>catch the error with a 
  try-except construct

### Example: Sinc in regular python

$\begin{eqnarray}
\text{sinc}(x) & := & \frac{\sin(x)}{x}
\end{eqnarray}$
<br>
and <br>
$\begin{eqnarray}
\lim_{x \rightarrow 0} \, \frac{\sin(x)}{x} & = & 1
\end{eqnarray}$

In [10]:
# sinc code (Version 1)
from math import sin

def sinc(x):
    """
    Naive Definition of the sinc function
    defined as sin(x)/x
    """
    return sin(x)/x

lst = [5.0,0.0]
for x in lst:
    print(f"  {x}  {sinc(x)}")

  5.0  -0.1917848549326277


ZeroDivisionError: float division by zero

In [11]:
# sinc code (Version 2)
from math import sin

def sinc(x):
    """
    Sinc Function :: sin(x)/x
    Improved version #1
    """
    try:
        return sin(x)/x
    except ZeroDivisionError:
        return 1.00
    
lst = [5.0,0.0]
for x in lst:
    print(f"  x:{x}  sinc(x):{sinc(x)}")    

  x:5.0  sinc(x):-0.1917848549326277
  x:0.0  sinc(x):1.0


### Numpy:

* has np.inf & as np.nan
* nan (not a number) **NOT** the same as inf
* nan & inf are both of the type **np.float64** <br>
  Why? NumPy uses the IEEE Standard for Binary Floating-Point for Arithmetic (IEEE 754)<br>
  <a href="https://ieeexplore.ieee.org/document/4610935/">754-2008 - IEEE Standard for Floating-Point Arithmetic</a>

In [ ]:
np.seterr('ignore')  # ignore action
# np.seterr('warn')  # print runtime warning

from math import pi
x     = np.array([-1.0,0.0,1.0])
res_x = np.log(x)
print(f"  x  :\n{x}\n")
print(f"  res (i.e. np.log(x)):\n{res_x}\n")

y = np.array(-5)
print(f"  y  :{y}")
print(f"  => np.sqrt(y):{np.sqrt(y)}")

# So, what to do for the latter case? => cast to complex type
print(f"  => np.sqrt(y):{np.sqrt(y.astype('complex128'))}")

contains <font color="green"><b>testing functions</b></font> like:
* np.isfinite
* np.isinf
* np.isneginf
* np.isposinf
* np.isnan

In [ ]:
#np.seterr('ignore')
print(f"  res_x            :{res_x}")
print(f"  res_x:isnan?     :{np.isnan(res_x)}")
print(f"     dtype(res_x)  :{res_x.dtype}")

y = 0.
res_y = np.log(y)
print(f"  res_y:isfinite?  :{np.isfinite(res_y)}")
print(f"  res_y:isinf?     :{np.isinf(res_y)}")
print(f"  res_y:isposinf?  :{np.isposinf(res_y)}")
print(f"  res_y:isneginf?  :{np.isneginf(res_y)}")
print(f"    dtype(res_y)   :{res_y.dtype}")

#### Working with vectors containg nan & inf

In [ ]:
x = np.arange(10)
print(f"  x      : {x}")
print(f"  x.dtype: '{x.dtype}'")
print(f"  sum(x) : {np.sum(x)}")

In [ ]:
# Try to set x[5] to nan ... 
x[5] = np.nan

* <font color="red"><b>Why?</b></font><br>
  Earlier we mentioned that *np.nan* is of the **np.float64** type<br>
  but x is of the type **np.int64** <br>
  (Mutatis mutandis for *np.inf*)
  
* <font color="green"><b>Solution?</b></font><br>
  Do a cast -> use np.astype

In [ ]:
x = x.astype(dtype='float64')
print(f"  x:{x}")
print(f"  x.dtype:{x.dtype}")
print(f"  sum(x)   (PRE CHANGE)   : {np.sum(x)}")
x[5] = np.nan
print(f"  sum(x)   (AFTER CHANGE) : {np.sum(x)}")
print(f"  prod(x)  (AFTER CHANGE) : {np.prod(x)}")

#### Vector operations with np.nan

Numpy contains functions that skip the nan elements:
* np.sum -> np.nansum
* np.cumsum -> np.nancumsum
* np.prod -> np.nanprod
* ...  

More & more functions are still added over time.

In [ ]:
print(f"  x:{x}")
print(f"    np.nansum(x)  :{np.nansum(x)}")
print(f"    np.nanprod(x) :{np.nanprod(x)}")

### Exercise

* Use a mask/boolean vector to calculate the sum & product of the following vector:<br>
  x:[ 1.  2. nan  4.  5.  6.  7. nan  9.] <br>
  without invoking neither np.nansum nor np.nanprod 

In [ ]:
# %load ../solutions/ex7.py